"""'Init'

Revision ID: 0dbf19eb997c
Revises: e357a2a61083
Create Date: 2022-12-14 08:52:58.706223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf19eb997c'
down_revision = 'e357a2a61083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
