"""'Init'

Revision ID: 89c9f50c180c
Revises: f110a66283c5
Create Date: 2022-12-14 08:44:53.404060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c9f50c180c'
down_revision = 'f110a66283c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
