"""'Init'

Revision ID: c09a8facb5e1
Revises: 0dbf19eb997c
Create Date: 2022-12-14 08:58:58.426282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09a8facb5e1'
down_revision = '0dbf19eb997c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
