"""'Init'

Revision ID: e357a2a61083
Revises: 89c9f50c180c
Create Date: 2022-12-14 08:47:11.183993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e357a2a61083'
down_revision = '89c9f50c180c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
