"""'Init'

Revision ID: f110a66283c5
Revises: 
Create Date: 2022-12-14 08:42:09.587872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f110a66283c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('adresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress_name', sa.String(length=250), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_name', sa.String(length=100), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_name', sa.String(length=20), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_m2m_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['record'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_m2m_phone')
    op.drop_table('phones')
    op.drop_table('emails')
    op.drop_table('adresses')
    op.drop_table('records')
    # ### end Alembic commands ###
